services:
  app:
    build: .
    container_name: wallet-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/wallet_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_LIQUIBASE_CHANGELOG=classpath:/db/changelog/changelog.xml
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: wallet-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wallet_db
    volumes:
      - wallet-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  wallet-db-data:
